remote_id = '140850221'
kb_layout_type = ''
size = [
    0,
    0,
    1006,
    816,
]
fav = ['140850221']

[options]
wayland-restore-token = '52e38dc5-3842-42e8-b8b3-2a89d1d77a84'
remote-menubar-drag-right = '1.0'
remote-menubar-drag-left = '0.0'

[ui_flutter]
peer-sorting = 'Remote ID'
wm_Main = '{"width":2048.0,"height":830.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true,"isFullscreen":false}'
remoteMenubarState = '{"pin":true}'
peer-card-ui-type = '0'
wm_RemoteDesktop = '{"width":764.0,"height":821.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":false,"isFullscreen":false}'
wm_PortForward = '{"width":764.0,"height":821.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":false,"isFullscreen":false}'
peer-tab-index = '0'
wm_Unknown = '{"width":764.0,"height":821.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":false,"isFullscreen":false}'
wm_FileTransfer = '{"width":764.0,"height":821.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":false,"isFullscreen":false}'
