rendezvous_server = 'rs-ny.rustdesk.com:21116'
nat_type = 1
serial = 0

[options]
allow-linux-headless = 'Y'
local-ip-addr = '192.168.2.205'
direct-server = 'Y'
verification-method = 'use-both-passwords'
allow-auto-record-incoming = 'Y'
