password = [
    48,
    48,
    53,
    119,
    74,
    80,
    55,
    106,
    119,
    81,
    49,
    83,
    114,
    102,
    86,
    102,
    51,
    81,
    55,
    72,
    51,
    116,
    66,
    55,
    111,
    53,
    103,
    57,
    67,
    87,
    71,
    122,
    57,
    103,
    120,
    72,
    119,
    122,
    73,
    84,
    80,
    116,
    52,
    116,
    83,
    101,
    71,
    74,
    75,
    71,
    108,
    71,
    73,
    57,
    51,
    113,
    110,
    70,
    77,
    118,
    90,
    57,
    103,
    67,
    71,
    84,
    81,
    84,
    50,
    106,
    84,
    85,
    106,
    84,
    97,
    108,
    115,
    83,
    69,
    90,
    89,
    82,
    99,
    51,
    85,
    53,
    120,
    121,
    87,
    89,
    87,
    73,
    103,
    81,
    82,
    66,
    99,
    71,
    78,
    122,
    70,
    73,
    80,
    73,
    79,
    68,
    77,
    102,
    97,
    80,
    78,
    65,
    61,
    61,
]
size = [
    26,
    23,
    2034,
    824,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = 'adaptive'
scroll_style = 'scrollauto'
image_quality = 'balanced'
custom_image_quality = [50]
show_remote_cursor = false
lock_after_session_end = false
privacy_mode = false
allow_swap_key = false
port_forwards = []
direct_failures = 1
disable_audio = false
disable_clipboard = false
enable_file_transfer = false
show_quality_monitor = false
keyboard_mode = 'map'
view_only = false

[options]
codec-preference = 'auto'
zoom-cursor = ''
rdp_username = 'production'
remote_dir = '{}'
custom-fps = '30'
remote-menubar-drag-x = '0.5'
rdp_password = '00E92FIStlKcJynNLJ74DGu7o5/9GVbyBWtkUTKzvt1KuuMsebylxk4pr+f5N66Dv/Q0XPIlmH'
local_dir = ''
local_show_hidden = ''
remote_show_hidden = ''
touch-mode = ''

[ui_flutter]
canvas = '{"xCursor":1.0,"yCursor":1.0,"xCanvas":-1.0,"yCanvas":-1.0,"scale":1.0,"currentDisplay":0}'
wm_RemoteDesktop = '{"width":764.0,"height":821.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":false,"isFullscreen":false}'

[info]
username = 'production'
hostname = 'desktop-qd5tedq'
platform = 'Windows'

[transfer]
write_jobs = []
read_jobs = []
