password = [
    48,
    48,
    53,
    97,
    55,
    57,
    52,
    104,
    98,
    43,
    84,
    82,
    48,
    55,
    85,
    112,
    99,
    47,
    105,
    89,
    76,
    84,
    72,
    55,
    111,
    53,
    54,
    101,
    76,
    103,
    90,
    122,
    53,
    53,
    113,
    71,
    119,
    87,
    72,
    71,
    80,
    121,
    56,
    53,
    98,
    101,
    84,
    115,
    50,
    67,
    105,
    87,
    66,
    66,
    110,
    78,
    118,
    47,
    75,
    90,
    49,
    106,
    118,
    122,
    43,
    82,
    88,
    48,
    110,
    72,
    87,
    88,
    47,
    102,
    84,
    121,
    48,
    74,
    67,
    76,
    99,
    86,
    68,
    85,
    99,
    108,
    103,
    82,
    84,
    86,
    99,
    73,
    69,
    48,
    87,
    109,
    77,
    71,
    67,
    120,
    90,
    80,
    80,
    52,
    110,
    100,
    76,
    113,
    88,
    76,
    99,
    65,
    61,
    61,
]
size = [
    0,
    0,
    0,
    0,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = 'adaptive'
scroll_style = 'scrollauto'
image_quality = 'balanced'
custom_image_quality = [50]
show_remote_cursor = false
lock_after_session_end = false
privacy_mode = false
allow_swap_key = false
port_forwards = []
direct_failures = 1
disable_audio = false
disable_clipboard = false
enable_file_transfer = false
show_quality_monitor = false
keyboard_mode = 'legacy'
view_only = false

[options]
touch-mode = ''
codec-preference = 'auto'
custom-fps = '30'
zoom-cursor = 'Y'

[ui_flutter]
canvas = '{"xCursor":1.0,"yCursor":1.0,"xCanvas":63.0,"yCanvas":-1.0,"scale":1.0,"currentDisplay":0}'
wm_RemoteDesktop = '{"width":1020.0,"height":405.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":false,"isFullscreen":false}'

[info]
username = 'andre'
hostname = 'desktop-3u98jmh'
platform = 'Windows'

[transfer]
write_jobs = []
read_jobs = []
